version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mts-bro
      - POSTGRES_DB=ostrovok-hotels-info
    ports:
      - "5477:5432"

